
USER_SERVICE_PORT: 9052
eureka:
    client:
        enabled: true
        healthcheck:
            enabled: true
        registryFetchIntervalSeconds: 10 # how often to fetch the registry from Eureka server
        instanceInfoReplicationIntervalSeconds: 10 # how often to replicate instance changes to be replicated to Eureka server
        lease:
            duration: 5
    instance:
        leaseRenewalIntervalInSeconds: 5 # intervalSeconds between subsequent heartbeats sent to Eureka server
        leaseExpirationDurationInSeconds: 2 # time that Eureka server waits since it received last heartbeat before it can evict this instance
management:
  security:
    enabled: false
  endpoints:
    web:
        exposure:
            include: ["health", "info", "refresh"]
info:
  app:
    name: user-service

server:
    port: ${USER_SERVICE_PORT:9092}

spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: 1
    jpa:
      hibernate:
        ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      properties:
        hibernate:
          format_sql: false
